version: '2'
services:
  db:
    image: postgres
    expose:
      - '5432'
  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - '5672'
    ports:
      - '8000:8000'
  message-store:
    build: ../chat-server-db
    environment:
      - DB_URL=db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PREFETCH=1
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq
  server:
    build:
      context: ./
      args:
        PORT: '5000'
    depends_on:
      - rabbitmq
    environment:
      - PORT=5000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PREFETCH=1
    expose:
      - '5000'
  ui:
    build:
      context: ../Chat-Tutorial
      args:
        SERVER_URL: 'server:5000'
    depends_on:
      - server


